name: Docker Image CI/CD

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*.*.*' ]  # Trigger on version tags (e.g., v1.0.0)
  pull_request:
    branches: [ main, master ]

# Environment variables
env:
  REGISTRY: docker.io
  IMAGE_NAME: iamrommel/us-zips

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    # Skip CI for documentation changes
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,format=long
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
      - name: Verify
        if: github.event_name != 'pull_request'
        run: |
          echo "Image pushed to Docker Hub:"
          echo "${{ steps.meta.outputs.tags }}" | tr ' ' '\n' | sed 's/^/  - /'
